import './globals.css'
import { Inter } from 'next/font/google'
import NavigationEvents from './components/navigationEvents'
import { Suspense } from 'react'
import LoadingBar from './components/loadingBar'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'QuickPlant',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

	return (
		<html lang="id">
			<head>
				<link rel="apple-touch-icon" href="/icon.png" />
				<link rel="shortcut icon" href="/icon.png" type="image/x-icon" />
			</head>
			<body className={inter.className}>
				<Suspense fallback={<LoadingBar />}>
					<NavigationEvents />
				</Suspense>
				{children}
			</body>
		</html>
	)
}