import './globals.css'
import { Inter } from 'next/font/google'
import LoadingBar from './components/loadingBar'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'QuickPlant',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
	return (
		<html lang="id">
			<head>
				<link rel="shortcut icon" href="/website-ico.png" type="image/x-icon" />
			</head>
			<body className={inter.className}>
				{/* <LoadingBar key={"key-" + Math.random.toString()} /> */}
				{children}
			</body>
		</html>
	)
}